

services:
  postgres:
    image: postgres:16.2-alpine3.18
    environment:
      POSTGRES_DB: "SQL_intensiv"
      POSTGRES_USER: "matildet"
      POSTGRES_PASSWORD: "pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./materials:/docker-entrypoint-initdb.d
      - /home/matildet/Desktop/projects/SQL:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U matildet -d SQL_intensiv"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
